name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}

            git pull origin main

            docker rm -f flask-container || true

            docker build -t flask-app .

            docker run -d -p 8001:8000 --restart unless-stopped --name flask-container flask-app
